apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 81            # The port on the service
      targetPort: 81       # The port on the container
      nodePort: 30080      # The NodePort exposed on the node
  type: NodePort
