apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: final
  name: CLO835
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "update", "delete"]
